version: "3.9"

services:
  panel:
    build: .
    entrypoint: ["/usr/local/bin/git-entrypoint.sh"]
    command: ["python", "-u", "run.py"]
    working_dir: /app
    ports: ["5000:5000"]
    environment:
      APP_DIR: /app
      REPO_URL: "${REPO_URL}"
      REPO_BRANCH: "${REPO_BRANCH:-main}"
      GIT_INTERVAL: "${GIT_INTERVAL:-60}"

      HOST: 0.0.0.0
      PORT: 5000

      SP_BRIDGE_URL: ws://bridge:8765/ws
      SP_TOKEN: SUPER_SECRET

      DB_HOST: 79.174.89.178
      DB_PORT: 16844
      DB_USER: HBusiwshu9whsd
      DB_PASSWORD: "NIUhbsuhwSU*GB0w87ygs08"
      DB_NAME: panel

      AUTHME_NAME: authmedb

      LUCKPERMS_HOST: 79.174.89.178
      LUCKPERMS_PORT: 16844
      LUCKPERMS_USER: donateLP
      LUCKPERMS_PASSWORD: "M8YI2rA7t-pT5QAa1E-PxjF2f4yt"
      LUCKPERMS_NAME: donate
    volumes:
      - code:/app
    depends_on:
      - bridge
    restart: unless-stopped

  bridge:
    build: .
    entrypoint: ["/usr/local/bin/git-entrypoint.sh"]
    command: ["python", "-u", "bridge/bridge.py"]
    working_dir: /app
    ports: ["8765:8765"]
    environment:
      APP_DIR: /app
      REPO_URL: "${REPO_URL}"
      REPO_BRANCH: "${REPO_BRANCH:-main}"
      GIT_INTERVAL: "${GIT_INTERVAL:-60}"

      BRIDGE_HOST: 0.0.0.0
      BRIDGE_PORT: 8765
      SP_TOKEN: SUPER_SECRET
    volumes:
      - code:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1',8765)); print('ok')"]
      interval: 10s
      timeout: 2s
      retries: 10
    restart: unless-stopped

volumes:
  code:
