version: "3.9"

services:
  panel:
    build:
      context: .
      dockerfile: Dockerfile
    # Запускаем наш python-entrypoint
    entrypoint: ["python", "-u", "docker/git_entrypoint.py"]
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      # ---- App cmd ----
      APP_CMD: "python -u run.py"
      APP_DIR: "/app"

      # ---- Git auto update (watcher) ----
      GIT_ENABLE: "1"
      GIT_MODE: "watch"              # watch|update|off
      GIT_REMOTE: "origin"
      GIT_BRANCH: "main"
      GIT_INTERVAL: "30"
      GIT_RESET: "1"
      GIT_RESTART: "0"               # панель не рестартуем на каждое изменение (опционально "1")
      GIT_VERBOSE: "1"
      PIP_ON_CHANGE: "1"
      PIP_FILE: "requirements.txt"

      # ---- сеть панели ----
      HOST: 0.0.0.0
      PORT: 5000

      # ---- подключение к BRIDGE ----
      SP_BRIDGE_URL: ws://bridge:8765/ws
      SP_TOKEN: SUPER_SECRET

      # ---- основная БД панели ----
      DB_HOST: 79.174.89.178
      DB_PORT: 16844
      DB_USER: HBusiwshu9whsd
      DB_PASSWORD: "NIUhbsuhwSU*GB0w87ygs08"
      DB_NAME: panel

      # ---- AuthMe (если не задать HOST/PORT/USER/PASSWORD, код возьмёт из DB_*) ----
      AUTHME_NAME: authmedb

      # ---- LuckPerms (свои креды) ----
      LUCKPERMS_HOST: 79.174.89.178
      LUCKPERMS_PORT: 16844
      LUCKPERMS_USER: donateLP
      LUCKPERMS_PASSWORD: "M8YI2rA7t-pT5QAa1E-PxjF2f4yt"
      LUCKPERMS_NAME: donate

      PYTHONUNBUFFERED: "1"
    volumes:
      - ./:/app
    depends_on:
      - bridge
    restart: unless-stopped

  bridge:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["python", "-u", "docker/git_entrypoint.py"]
    working_dir: /app
    ports:
      - "8765:8765"
    environment:
      # ---- App cmd ----
      APP_CMD: "python -u bridge/bridge.py"
      APP_DIR: "/app"

      # ---- Git auto update (одноразово + рестарт на изменение) ----
      GIT_ENABLE: "1"
      GIT_MODE: "watch"     # можно "update" если не нужен постоянный вотчер
      GIT_REMOTE: "origin"
      GIT_BRANCH: "main"
      GIT_INTERVAL: "30"
      GIT_RESET: "1"
      GIT_RESTART: "1"      # при апдейте перезапускаем bridge
      GIT_VERBOSE: "1"
      PIP_ON_CHANGE: "1"
      PIP_FILE: "requirements.txt"

      BRIDGE_HOST: 0.0.0.0
      BRIDGE_PORT: 8765
      SP_TOKEN: SUPER_SECRET
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1',8765)); print('ok')"]
      interval: 10s
      timeout: 2s
      retries: 10
    restart: unless-stopped
